name: robinpedia
description: A Wikipedia viewer and offline ZIM file reader.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.5
  permission_handler: ^10.4.3
  connectivity_plus: ^4.0.2
  provider: ^6.0.5
  xml: ^6.3.0
  shared_preferences: ^2.1.2
  ffi: ^2.1.0
  package_info_plus: ^4.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
