name: robinpedia
description: "Your offline knowledge companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  collection: ^1.18.0
  http: ^1.3.0
  permission_handler: ^11.2.0
  device_info_plus: ^11.2.2
  convert: ^3.1.1
  connectivity_plus: ^5.0.2
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  test: ^1.24.9
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  drift_dev: ^2.14.1

dependency_overrides:
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  characters: ^1.4.0

flutter:
  uses-material-design: true
