org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Fix for Java compatibility issues with Android Gradle Plugin
# Using Java from Android Studio for consistency
android.useCompileJavaFromToolchain=true
org.gradle.unsafe.configuration-cache=false
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
