// Mocks generated by Mockito 5.4.5 from annotations
// in robinpedia/test/widgets/download_list_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:robinpedia/src/models/zim_catalog_item.dart' as _i5;
import 'package:robinpedia/src/services/download_manager.dart' as _i4;
import 'package:robinpedia/src/services/zim_download_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ZimDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockZimDownloadService extends _i1.Mock
    implements _i2.ZimDownloadService {
  @override
  _i3.Stream<Map<String, _i4.DownloadInfo>> get downloads =>
      (super.noSuchMethod(
            Invocation.getter(#downloads),
            returnValue: _i3.Stream<Map<String, _i4.DownloadInfo>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<Map<String, _i4.DownloadInfo>>.empty(),
          )
          as _i3.Stream<Map<String, _i4.DownloadInfo>>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> downloadZimFile(_i5.ZimCatalogItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#downloadZimFile, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void cancelDownload(String? id) => super.noSuchMethod(
    Invocation.method(#cancelDownload, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void pauseDownload(String? id) => super.noSuchMethod(
    Invocation.method(#pauseDownload, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void resumeDownload(String? id) => super.noSuchMethod(
    Invocation.method(#resumeDownload, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.DownloadInfo? getDownloadInfo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadInfo, [id]),
            returnValueForMissingStub: null,
          )
          as _i4.DownloadInfo?);

  @override
  bool isDownloading(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloading, [id]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isDownloaded(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloaded, [id]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
